In [90]:
from sklearn import datasets

In [91]:
breast = datasets.load_breast_cancer()

In [92]:
X,y = datasets.load_iris(return_X_y = True)

### **TRAIN TEST**

In [93]:
import pandas as pd

In [94]:
df= pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

In [95]:
df.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner


In [96]:
from sklearn.model_selection import train_test_split

In [97]:
# Feature Scalling the main reason equal value all column through min max and normalization (equal important) 
#0 and 1 between

In [98]:
X = df.drop('selling_price', axis=1)
y= df['selling_price']


In [99]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20, random_state=42)

In [100]:
X_train.shape

(3472, 7)

In [101]:
 X_test.shape

(868, 7)

In [102]:
y_train.shape

(3472,)

In [103]:
from sklearn.preprocessing import MinMaxScaler

# 1. Select only numeric columns
numeric_cols = X_train.select_dtypes(include=['number']).columns

# 2. Initialize the scaler
scaler = MinMaxScaler()

# 3. Fit on training set, transform both train and test
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])


### Apply Normalization

In [104]:
from sklearn.preprocessing import MinMaxScaler

# Select only numeric columns
numeric_df = df.select_dtypes(include=['number'])

# Apply scaler to numeric data
scaler = MinMaxScaler()
scaled_values = scaler.fit_transform(numeric_df)

# If you want it back as a DataFrame with the same column names:
scaled_df = pd.DataFrame(scaled_values, columns=numeric_df.columns)

# Optional: Combine with original non-numeric columns
result_df = df.copy()
result_df[numeric_df.columns] = scaled_df


In [105]:
scaled_df

,year,selling_price,km_driven
0,0.535714,0.004505,0.086783
1,0.535714,0.012950,0.061988
2,0.714286,0.065315,0.123976
3,0.892857,0.025901,0.057028
4,0.785714,0.048423,0.174807
...,...,...,...
4335,0.785714,0.043919,0.099181
4336,0.785714,0.043919,0.099181
4337,0.607143,0.010135,0.102900
4338,0.857143,0.095158,0.111579


# 3

### IMPORT LIBRARY

In [106]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### IMPORT DATASET

In [107]:
df1 = pd.read_csv("Social_Network_Ads.csv")
df1.head(1)

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0


In [108]:
df1.shape

(400, 5)

### DROP COLUMN

In [109]:
df1.drop('User ID', axis=1, inplace =True)

In [110]:
df1.shape

(400, 4)

In [111]:
df1['Gender']=df1['Gender'].map({'Male':1, 'Female':0})

In [112]:
df1

,Gender,Age,EstimatedSalary,Purchased
0,1,19,19000,0
1,1,35,20000,0
2,0,26,43000,0
3,0,27,57000,0
4,1,19,76000,0
...,...,...,...,...
395,0,46,41000,1
396,1,51,23000,1
397,0,50,20000,1
398,1,36,33000,0


### APPLY STANDARSCALER

In [113]:
X = df1.drop('Purchased', axis = 1)
y= df1['Purchased']

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [115]:
X_train.head(1)

,Gender,Age,EstimatedSalary
3,0,27,57000


In [116]:
X_train.shape

(320, 3)

In [117]:
X_test.shape

(80, 3)

In [118]:
y_train.head(1)

3    0
Name: Purchased, dtype: int64

In [119]:
y_train.shape

(320,)

## SAME AS MIN MAX (Standar scaler)

In [120]:
from sklearn.preprocessing  import StandardScaler
scaler = StandardScaler()

In [121]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [122]:
X_train_scaled


array([[-1.        , -1.06675246, -0.38634438],
       [ 1.        ,  0.79753468, -1.22993871],
       [-1.        ,  0.11069205,  1.853544  ],
       [-1.        ,  0.60129393, -0.90995465],
       [-1.        ,  1.87685881, -1.28811763],
       [ 1.        , -0.57615058,  1.44629156],
       [ 1.        ,  0.3069328 , -0.53179168],
       [ 1.        ,  0.99377543,  0.10817643],
       [ 1.        , -1.16487283,  0.45724994],
       [ 1.        , -1.55735433,  0.31180264],
       [ 1.        ,  1.0918958 ,  0.45724994],
       [-1.        , -0.18366908, -0.47361276],
       [ 1.        ,  0.20881242, -0.32816546],
       [-1.        ,  0.3069328 ,  0.28271318],
       [ 1.        , -1.16487283, -1.57901222],
       [-1.        ,  0.11069205,  0.25362372],
       [ 1.        ,  2.07309956,  1.73718616],
       [ 1.        ,  0.40505317, -0.18271817],
       [-1.        ,  1.4843773 ,  2.11534913],
       [ 1.        , -0.37990983,  1.21357589],
       [-1.        ,  1.87685881,  1.504

### IN MIN MAX RANGE 0 to 1
### IN STANDARD SCALER Mean 0 and standard deviation 1 (Z-Score)

### LABEL ENCODER AND ORDINAL ENCODER


In [123]:
df2 = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

In [124]:
df2.head(1)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner


### when categorical data then change into numerical through one hot encoder

### ordinal data, nominal data, label data

In [125]:
df.drop('name', axis =1, inplace=True)

In [126]:
df['transmission'].value_counts()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

In [127]:
df['transmission']=df['transmission'].map({'Manual':0, 'Automatic':1})

In [128]:
from  sklearn.model_selection import train_test_split

In [129]:
X_train, X_test, y_train, y_test = train_test_split(df2.drop('fuel', axis=1), df['fuel'], test_size=0.20, random_state=42)

In [130]:
X_train.head(1)

,name,year,selling_price,km_driven,seller_type,transmission,owner
227,Mahindra Scorpio S11 BSIV,2017,1500000,20000,Individual,Manual,First Owner


### USING LABEL 

In [131]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [132]:
hi = LabelEncoder()

In [133]:
y_train_scaled = hi.fit_transform(y_train)
y_test_scaled = hi.transform(y_test)

In [134]:
y_train_scaled 

array([1, 1, 4, ..., 1, 1, 4])

###  label encoder using y test means target value

In [135]:
hii = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
X_train_scaled = hii.fit_transform(X_train)
X_test_scaled = hii.transform(X_test)

In [136]:
X_train_scaled

array([[606.,  23., 350., ...,   1.,   1.,   0.],
       [863.,  24., 187., ...,   1.,   1.,   0.],
       [698.,  19.,  33., ...,   1.,   1.,   2.],
       ...,
       [759.,  22., 229., ...,   0.,   1.,   0.],
       [782.,  19., 101., ...,   1.,   1.,   0.],
       [411.,  19.,  69., ...,   1.,   1.,   0.]])

### ONE HOT ENCODER

In [141]:
#from sklearn.preprocessing import OneHotEncoder

#ohe = OneHotEncoder(drop='first', dtype=int, sparse_output=False)
#df_trf = ohe.fit_transform(df2[['buyer', 'fruits', 'gender']])
#df_trf

